- src/main/java/org/ict/allaboutu/notice/controller.java
- src/main/java/org/ict/allaboutu/notice/controller/NoticeController.java
- src/main/java/org/ict/allaboutu/notice/domain/Notice.java
- src/main/java/org/ict/allaboutu/notice/repository/NoticeRepository.java
- src/main/java/org/ict/allaboutu/notice/service/NoticeService.java
> commit 18:49

- src/main/java/org/ict/allaboutu/board/controller/BoardController.java
- src/main/java/org/ict/allaboutu/board/domain/Board.java
- src/main/java/org/ict/allaboutu/board/domain/Comment.java
- src/main/java/org/ict/allaboutu/board/repository/CommentRepository.java
- src/main/java/org/ict/allaboutu/board/service/BoardService.java
> 231129 Board Backend 작업

- src/main/java/org/ict/allaboutu/color/controller/ColorController.java
- src/main/java/org/ict/allaboutu/color/domain/Color.java
- src/main/java/org/ict/allaboutu/color/repository/ColorRepository.java
- src/main/java/org/ict/allaboutu/color/service/ColorService.java
- src/main/java/org/ict/allaboutu/face/controller.java
- src/main/java/org/ict/allaboutu/face/controller/FaceController.java
- src/main/java/org/ict/allaboutu/face/domain/Face.java
- src/main/java/org/ict/allaboutu/face/repository/FaceRepository.java
- src/main/java/org/ict/allaboutu/face/service/FaceService.java
- src/main/java/org/ict/allaboutu/website/controller/WebsiteController.java
- src/main/java/org/ict/allaboutu/website/domain/Website.java
- src/main/java/org/ict/allaboutu/website/repository/WebsiteRepository.java
- src/main/java/org/ict/allaboutu/website/service/WebsiteService.java
> color face website

- src/main/java/org/ict/allaboutu/notice/controller/NoticeController.java
- src/main/java/org/ict/allaboutu/notice/domain/Notice.java
- src/main/java/org/ict/allaboutu/notice/service/NoticeDto.java
- src/main/java/org/ict/allaboutu/notice/service/NoticeService.java
> 17:23 sungyoungcommit

- src/main/java/org/ict/allaboutu/board/controller/BoardController.java
- src/main/java/org/ict/allaboutu/board/domain/Attachment.java
- src/main/java/org/ict/allaboutu/board/domain/Board.java
- src/main/java/org/ict/allaboutu/board/domain/BoardHashtag.java
- src/main/java/org/ict/allaboutu/board/domain/Comment.java
- src/main/java/org/ict/allaboutu/board/repository/BoardRepository.java
- src/main/java/org/ict/allaboutu/board/repository/CommentRepository.java
- src/main/java/org/ict/allaboutu/board/service/BoardDto.java
- src/main/java/org/ict/allaboutu/board/service/BoardService.java
- src/main/java/org/ict/allaboutu/chatbot/domain/ChatLog.java
@minji0478 
spring boot version upgrade에 따른 import 수정
> 231130 spring boot version upgrade 2.6.0 -> 3.2.0

- src/main/java/org/ict/allaboutu/personalcolor/domain/PersonalColor.java
- src/main/java/org/ict/allaboutu/personalcolor/domain/UserPersonalColor.java
> git reload push minji

- src/main/java/org/ict/allaboutu/style/controller.java
- src/main/resources/application.properties
application update 20231205
@SUNGHWONJEON 
@coffee2think
> application update 20231205

- src/main/java/org/ict/allaboutu/style/controller/PythonRunner.java
- src/main/java/org/ict/allaboutu/style/controller/StyleController.java
- src/main/java/org/ict/allaboutu/style/domain/Style.java
- src/main/java/org/ict/allaboutu/style/repository/StyleRepository.java
- src/main/java/org/ict/allaboutu/style/service/RequestDto.java
- src/main/java/org/ict/allaboutu/style/service/StyleDto.java
- src/main/java/org/ict/allaboutu/style/service/StyleService.java
> jsh 231206 -1재 풀리퀘스트

- src/main/java/org/ict/allaboutu/notice/controller/NoticeController.java
- src/main/java/org/ict/allaboutu/notice/domain/Notice.java
- src/main/java/org/ict/allaboutu/notice/repository/NoticeRepository.java
- src/main/java/org/ict/allaboutu/notice/service/NoticeService.java
> 16:41 sungyoung

- src/main/java/org/ict/allaboutu/admin/controller/AdminController.java
- src/main/java/org/ict/allaboutu/personalcolor/controller/PersonalColorController.java
- src/main/java/org/ict/allaboutu/personalcolor/domain/PersonalColor.java
- src/main/java/org/ict/allaboutu/personalcolor/domain/UserPersonalColor.java
- src/main/java/org/ict/allaboutu/personalcolor/repository/PersonalColorRepository.java
- src/main/java/org/ict/allaboutu/personalcolor/repository/UserpersonalColorRepository.java
- src/main/java/org/ict/allaboutu/personalcolor/service/PersonalColorService.java
- src/main/java/org/ict/allaboutu/personalcolor/service/PersonalDto.java
@SUNGHWONJEON 
@coffee2think 
퍼스널컬러 진단 기본 구조 구축 중
> minji springboot push 20231208

- build.gradle
- src/main/java/org/ict/allaboutu/color/controller/ColorController.java
- src/main/java/org/ict/allaboutu/color/domain/Color.java
- src/main/java/org/ict/allaboutu/color/repository/ColorRepository.java
- src/main/java/org/ict/allaboutu/color/service/ColorDto.java
- src/main/java/org/ict/allaboutu/color/service/ColorService.java
- src/main/java/org/ict/allaboutu/face/controller/FaceController.java
- src/main/java/org/ict/allaboutu/face/domain/Face.java
- src/main/java/org/ict/allaboutu/face/repository/FaceRepository.java
- src/main/java/org/ict/allaboutu/face/service/FaceDto.java
- src/main/java/org/ict/allaboutu/face/service/FaceService.java
- src/main/java/org/ict/allaboutu/myPage/controller/MyPageController.java
- src/main/java/org/ict/allaboutu/myPage/service/MyPageDto.java
- src/main/java/org/ict/allaboutu/myPage/service/MyPageService.java
- src/main/java/org/ict/allaboutu/website/controller/WebsiteController.java
- src/main/java/org/ict/allaboutu/website/domain/Website.java
- src/main/java/org/ict/allaboutu/website/repository/WebsiteRepository.java
- src/main/java/org/ict/allaboutu/website/service/WebsiteDto.java
- src/main/java/org/ict/allaboutu/website/service/WebsiteService.java
> Jaemin lee

- src/main/java/org/ict/allaboutu/personalcolor/controller/PersonalColorController.java
- src/main/java/org/ict/allaboutu/personalcolor/service/PersonalColorService.java
@SUNGHWONJEON 
@coffee2think 
springboot 퍼스널컬러 작업 진행중
> minji push springboot 20231211

- src/main/java/org/ict/allaboutu/personalcolor/controller/PersonalColorController.java
@SUNGHWONJEON 
@coffee2think 
퍼스널컬러 작업중
> minji push 20231211

- src/main/java/org/ict/allaboutu/personalcolor/controller/PersonalColorController.java
@SUNGHWONJEON 
@coffee2think 
퍼스널 컬러 이미지 추가 중입니다
> minji push 20231212 springboot

- src/main/java/org/ict/allaboutu/personalcolor/controller/PersonalColorController.java
- src/main/java/org/ict/allaboutu/personalcolor/service/PersonalColorService.java
@SUNGHWONJEON 
@coffee2think 
퍼스널 컬러 작업 진행 중
> minji push 20231213 springboot

- src/main/java/org/ict/allaboutu/admin/controller/AdminController.java
- src/main/java/org/ict/allaboutu/admin/service/AdminService.java
- src/main/java/org/ict/allaboutu/personalcolor/controller/PersonalColorController.java
@SUNGHWONJEON 
@coffee2think 
퍼스널 컬러 작업 완료
> minji push 20231215 springboot

- src/main/java/org/ict/allaboutu/board/controller/BoardController.java
- src/main/java/org/ict/allaboutu/board/service/BoardService.java
- src/main/java/org/ict/allaboutu/member/controller/MemberController.java
- src/main/java/org/ict/allaboutu/member/repository/MailRepository.java
- src/main/java/org/ict/allaboutu/member/service/MailDto.java
- src/main/java/org/ict/allaboutu/member/service/MailService.java
- src/main/java/org/ict/allaboutu/member/service/MemberService.java
> 231215 14:47 Board, 아이디,비밀번호 찾기

- src/main/java/org/ict/allaboutu/member/controller/MemberController.java
- src/main/java/org/ict/allaboutu/member/repository/MailRepository.java
- src/main/java/org/ict/allaboutu/member/repository/MemberRepository.java
- src/main/java/org/ict/allaboutu/member/service/MailDto.java
- src/main/java/org/ict/allaboutu/member/service/MailService.java
- src/main/java/org/ict/allaboutu/member/service/MemberService.java
- src/main/resources/application.properties
> 231215 17:33 아이디찾기, 비밀번호 찾기

- src/main/java/org/ict/allaboutu/board/service/BoardService.java
- src/main/java/org/ict/allaboutu/common/WebConfig.java
- src/main/java/org/ict/allaboutu/member/controller/MemberController.java
- src/main/java/org/ict/allaboutu/member/repository/MemberRepository.java
- src/main/java/org/ict/allaboutu/oauth/controller/AuthController.java
- src/main/java/org/ict/allaboutu/oauth/service/AuthService.java
> 231216 18:55 네이버 로그인 구현

- src/main/java/org/ict/allaboutu/member/controller/MemberController.java
- src/main/java/org/ict/allaboutu/member/service/MemberService.java
> 231217 17:40 dev21 재종합
